# ML2. Supervised learning

## 1. Аналитическое решение задач регресии

### 1.1 Общая формула

Аналитическое решение задачи регрессии можно представить в векторной форме уравнения:

$$
\mathbf{X}^\top \mathbf{X} \boldsymbol{\beta} = \mathbf{X}^\top \mathbf{y}
\quad \Rightarrow \quad
\boldsymbol{\beta} = (\mathbf{X}^\top \mathbf{X})^{-1} \mathbf{X}^\top \mathbf{y}
$$

**Обозначения символов:**
- $\mathbf{X} \in \mathbb{R}^{n \times m}$ — матрица признаков  
  ($n$ — число объектов, $m$ — число признаков; **первый столбец = 1** для свободного члена $\beta_0$)
- $\mathbf{y} \in \mathbb{R}^{n}$ — вектор целевой переменной (наблюдаемые значения)
- $\boldsymbol{\beta} \in \mathbb{R}^{m}$ — вектор коэффициентов модели:  
  $\boldsymbol{\beta} = \begin{bmatrix} \beta_0 & \beta_1 & \cdots & \beta_{m-1} \end{bmatrix}^\top$
- $\mathbf{X}^\top$ — транспонированная матрица $\mathbf{X}$
- $(\mathbf{X}^\top \mathbf{X})^{-1}$ — обратная матрица (существует при полном ранге $\mathbf{X}$)
- $\mathbb{R}^{a \times b}$ — пространство матриц размера $a \times b$ с вещественными элементами

**Функция потерь MSE (Mean Squared Error)**

$$
L(\boldsymbol{\beta}) = \frac{1}{n} \sum_{i=1}^{n} (y_i - \hat{y}_i)^2 = \frac{1}{n} \sum_{i=1}^{n} (y_i - \mathbf{x}_i^\top \boldsymbol{\beta})^2
$$

**В векторной форме:**

$$
L(\boldsymbol{\beta}) = \frac{1}{n} (\mathbf{y} - \mathbf{X}\boldsymbol{\beta})^\top (\mathbf{y} - \mathbf{X}\boldsymbol{\beta})
$$

**Обозначения:**
- $n$ — количество объектов в выборке
- $y_i$ — истинное значение целевой переменной
- $\hat{y}_i$ — предсказанное значение
- $\mathbf{x}_i$ — вектор признаков $i$-го объекта
- $\boldsymbol{\beta}$ — вектор коэффициентов модели
- $\mathbf{X}$ — матрица признаков
- $\mathbf{y}$ — вектор целевых значений

### 1.2 Регуляризация. L1(Lasso) и L2(Ridge)

При добавлении регуляризации(**штрафной член**) L1 и L2 в функцию потерь мы минимизируем не только ошибку предсказания, но и штрафуем "сложность модели", т.е. слишком большие веса у признаков. Это помогает избежать переобучения модели.

В **первом случае** модель отсеивает признаки, которые нерелевантны или избыточны, оставляя только те, которые важны для предсказания целевой переменной. **L1** не имеет аналитического решения, т.к. недифференцируема в точке w = 0, что делает невозможным получение замкнутой формулы через классическое приравнивание градиента к нулю.

**L1** используют, когда нужно **уменьшить колличество признаков** потому, что данная регуляризация обнуляет слабые признаки, а не просто уменьшает их. Это происходит из-за того, что L1 "штарфует" веса фиксированной ставкой.

**Формула функции потерь для L1:**

$$
L_{\text{Lasso}} = \frac{1}{n} \sum_{i=1}^{n} (y_i - \hat{y}_i)^2 + \alpha \sum_{j=1}^{m} |w_j|
$$

**Градиент:**

$$
\frac{\partial L}{\partial w_j} = \frac{2}{n} \sum_{i=1}^{n} (\hat{y}_i - y_i) \cdot x_{ij} + \alpha \cdot \text{sign}(w_j)
$$

где:
- $n$ — количество объектов в выборке
- $m$ — количество признаков
- $y_i$ — истинное значение для $i$-го объекта
- $\hat{y}_i$ — предсказанное значение для $i$-го объекта
- $w_j$ — вес $j$-го признака
- $\alpha$ — параметр регуляризации
- $x_{ij}$ — значение $j$-го признака для $i$-го объекта
- $\text{sign}(w_j)$ — функция знака ($+1$, $-1$ или $0$)

**Особенности:**
- Обнуляет неважные веса → отбор признаков
- Недифференцируема в точке $w_j = 0$
- Не имеет аналитического решения

Во **втором случае** модель "штрафует" веса пропорционально квадрату коэффициента, т.е. даже признак имеющий очень слабую корреляцию с целевой переменной остается, но имеет очень маленький коэффициент веса.

Аналитическое решение с добавленим регуляризации **L2**(Ridge/Гребневая регрессия):

$$
\boldsymbol{\beta} = (X^T X + \lambda I)^{-1} X^T y
$$

| Символ | Описание |
|--------|----------|
| $\boldsymbol{\beta}$ | Вектор оптимальных параметров модели (веса + смещение) |
| $X$ | Матрица признаков размера $(n_{\text{samples}}, n_{\text{features}})$<br>*(обычно с добавленным столбцом единиц для смещения)* |
| $y$ | Вектор целевых значений размера $(n_{\text{samples}},)$ |
| $\lambda$ | Параметр регуляризации (λ ≥ 0)<br>• λ = 0 → обычная линейная регрессия<br>• λ → ∞ → все веса стремятся к нулю |
| $I$ | Единичная матрица размера $(n_{\text{features}}, n_{\text{features}})$ |
| $X^T$ | Транспонированная матрица признаков |
| $(\cdot)^{-1}$ | Обратная матрица |

Формула штрафа:
$$
R(\boldsymbol{\beta}) = \sum_{j=1}^{m} \beta_j^2
$$
Формула потерь для L2:
$$
L_{\text{Ridge}} = \frac{1}{n} \sum_{i=1}^{n} (y_i - \hat{y}_i)^2 + \lambda \sum_{j=1}^{m} \beta_j^2
$$

### 1.3 Нелинейные зависимости

Эти же модели могут выявлять зависимости не только когда данные похожи на прямую. Для этого используются криволинейные функции - многочлены, а саму модель называют **полиноминальной регрессией**.

Процесс обучения модели полиноминальной регрессии аналогичен процессу обучения модели линейной регресии. Единственной отличие заключается в том, что нужно добавить больше столбцов в набор данных, прежде чем применять линейную регрессию, а именно значения признаков возведенные в необходимую степень.

## 2. Введение

Импортируем необходимые библиотеки, а так же тренировочные и тестовые данные:

In [1]:
import pandas as pd
import numpy as np
from collections import Counter
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.linear_model import LinearRegression, Ridge, Lasso, ElasticNet
from sklearn.preprocessing import MinMaxScaler, StandardScaler, PolynomialFeatures

In [2]:
train_df = pd.read_json('data/train.json')
test_df = pd.read_json('data/test.json')

In [3]:
train_df.info()

<class 'pandas.DataFrame'>
Index: 49352 entries, 4 to 124009
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   bathrooms        49352 non-null  float64
 1   bedrooms         49352 non-null  int64
 2   building_id      49352 non-null  str
 3   created          49352 non-null  str
 4   description      49352 non-null  str
 5   display_address  49352 non-null  str
 6   features         49352 non-null  object
 7   latitude         49352 non-null  float64
 8   listing_id       49352 non-null  int64
 9   longitude        49352 non-null  float64
 10  manager_id       49352 non-null  str
 11  photos           49352 non-null  object
 12  price            49352 non-null  int64
 13  street_address   49352 non-null  str
 14  interest_level   49352 non-null  str
dtypes: float64(3), int64(3), object(2), str(7)
memory usage: 6.0+ MB

Почистим данные от выбросов

In [4]:
lower_p, upper_p = 0.01, 0.99
price_lower = train_df['price'].quantile(lower_p)
price_upper = train_df['price'].quantile(upper_p)

bedrooms_lower = train_df['bedrooms'].quantile(lower_p)
bedrooms_upper = train_df['bedrooms'].quantile(upper_p)

bathrooms_lower = train_df['bathrooms'].quantile(lower_p)
bathrooms_upper = train_df['bathrooms'].quantile(upper_p)

train_df = train_df[
    (train_df['price'] >= price_lower) &
    (train_df['price'] <= price_upper) &
    (train_df['bedrooms'] >= bedrooms_lower) &
    (train_df['bedrooms'] <= bedrooms_upper) &
    (train_df['bathrooms'] >= bathrooms_lower) &
    (train_df['bathrooms'] <= bathrooms_upper)
].copy().reset_index(drop=True)

price_lower_test = test_df['price'].quantile(lower_p)
price_upper_test = test_df['price'].quantile(upper_p)

bedrooms_lower_test = test_df['bedrooms'].quantile(lower_p)
bedrooms_upper_test = test_df['bedrooms'].quantile(upper_p)

bathrooms_lower_test = test_df['bathrooms'].quantile(lower_p)
bathrooms_upper_test = test_df['bathrooms'].quantile(upper_p)

test_df = test_df[
    (test_df['price'] >= price_lower_test) &
    (test_df['price'] <= price_upper_test) &
    (test_df['bedrooms'] >= bedrooms_lower_test) &
    (test_df['bedrooms'] <= bedrooms_upper_test) &
    (test_df['bathrooms'] >= bathrooms_lower_test) &
    (test_df['bathrooms'] <= bathrooms_upper_test)
].copy().reset_index(drop=True)

train_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 47745 entries, 0 to 47744
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   bathrooms        47745 non-null  float64
 1   bedrooms         47745 non-null  int64
 2   building_id      47745 non-null  str
 3   created          47745 non-null  str
 4   description      47745 non-null  str
 5   display_address  47745 non-null  str
 6   features         47745 non-null  object
 7   latitude         47745 non-null  float64
 8   listing_id       47745 non-null  int64
 9   longitude        47745 non-null  float64
 10  manager_id       47745 non-null  str
 11  photos           47745 non-null  object
 12  price            47745 non-null  int64
 13  street_address   47745 non-null  str
 14  interest_level   47745 non-null  str
dtypes: float64(3), int64(3), object(2), str(7)
memory usage: 5.5+ MB

Поделим данные на тренировочные и валидационные

In [5]:
train_df, valid_df = train_test_split(
    train_df,
    test_size=0.2,
    random_state=21
)

## 3. Анализ данных

### 3.1 Создадим список особенностетей домов из столбца "features"

In [6]:
features = train_df['features'].to_list()
list_of_features = []
for pos in features:
    for ch in pos:
        list_of_features.append(ch)

counter = Counter(list_of_features)
top = dict(counter.most_common(20))
print(f"Уникальных значений: {len(counter)}\n")
print("Топ-20:\n")
for key, value in top.items():
    print(f"{key} - {value}")

Уникальных значений: 1349

Топ-20:

Elevator - 20069
Cats Allowed - 18413
Hardwood Floors - 18318
Dogs Allowed - 17248
Doorman - 16245
Dishwasher - 15915
No Fee - 14088
Laundry in Building - 12703
Fitness Center - 10303
Pre-War - 7120
Laundry in Unit - 6643
Roof Deck - 5047
Outdoor Space - 3997
Dining Room - 3853
High Speed Internet - 3370
Balcony - 2269
Swimming Pool - 2100
Laundry In Building - 2031
New Construction - 2022
Terrace - 1711

### 3.2 Создадим нофый фрейм данных с признаками

In [7]:
feature_list = list(top.keys())

y_train = train_df['price']
y_val = valid_df['price']
y_test = test_df['price']

X_train = pd.DataFrame()
X_val = pd.DataFrame()
X_test = pd.DataFrame()

for name in feature_list:
    X_train[name] = train_df['features'].apply(lambda x: 1 if name in x else 0)
    X_val[name] = valid_df['features'].apply(lambda x: 1 if name in x else 0)
    X_test[name] = test_df['features'].apply(lambda x: 1 if name in x else 0)

X_train['bathrooms'] = train_df['bathrooms']
X_train['bedrooms'] = train_df['bedrooms']

X_val['bathrooms'] = valid_df['bathrooms']
X_val['bedrooms'] = valid_df['bedrooms']

X_test['bathrooms'] = test_df['bathrooms']
X_test['bedrooms'] = test_df['bedrooms']

feature_list.extend(['bathrooms', 'bedrooms'])

X_train.info()

<class 'pandas.DataFrame'>
Index: 38196 entries, 11673 to 15305
Data columns (total 22 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Elevator             38196 non-null  int64
 1   Cats Allowed         38196 non-null  int64
 2   Hardwood Floors      38196 non-null  int64
 3   Dogs Allowed         38196 non-null  int64
 4   Doorman              38196 non-null  int64
 5   Dishwasher           38196 non-null  int64
 6   No Fee               38196 non-null  int64
 7   Laundry in Building  38196 non-null  int64
 8   Fitness Center       38196 non-null  int64
 9   Pre-War              38196 non-null  int64
 10  Laundry in Unit      38196 non-null  int64
 11  Roof Deck            38196 non-null  int64
 12  Outdoor Space        38196 non-null  int64
 13  Dining Room          38196 non-null  int64
 14  High Speed Internet  38196 non-null  int64
 15  Balcony              38196 non-null  int64
 16  Swimming Pool        38196 non-null  int64
 17  Laundry In Building  38196 non-null  int64
 18  New Construction     38196 non-null  int64
 19  Terrace              38196 non-null  int64
 20  bathrooms            38196 non-null  float64
 21  bedrooms             38196 non-null  int64
dtypes: float64(1), int64(21)
memory usage: 6.7 MB

## 4. Реализация моделей - Линейная регрессия

Реализуем класс для аналитического решения линейной регрессии:

In [8]:
class Linreg:
    def __init__(self):
        self.weights = None

    def fit(self, X, y):
        X = np.c_[np.ones((X.shape[0], 1)), X]
        self.weights = np.linalg.pinv(X).dot(y)
        return self

    def predict(self, X):
        X = np.c_[np.ones((X.shape[0], 1)), X]
        return X.dot(self.weights)

Создаздим еще один вариант с добавлением стохастического градиентного спуска (SDG) для поиска оптимальных весовых коэффициентов модели:

In [9]:
class LinregSDG:
    def __init__(self, learning_rate=0.1, n_epochs=150, batch_size=128, random_state=None):
        self.learning_rate = learning_rate
        self.n_epochs = n_epochs
        self.batch_size = batch_size
        self.random_state = random_state
        self.weights = None

    def fit(self, X, y):
        if self.random_state is not None:
            np.random.seed(self.random_state)

        X = np.asarray(X)
        y = np.asarray(y)

        X = np.c_[np.ones((X.shape[0], 1)), X]
        n_samples, n_features = X.shape

        self.weights = np.random.randn(n_features)

        for epoch in range(self.n_epochs):
            indices = np.random.permutation(n_samples)

            for i in range(0, n_samples, self.batch_size):

                batch_idx = indices[i:i + self.batch_size]
                X_batch = X[batch_idx]
                y_batch = y[batch_idx]

                predictions = X_batch.dot(self.weights)
                errors = predictions - y_batch
                gradient = (2 / len(y_batch)) * X_batch.T.dot(errors)
                self.weights -= self.learning_rate * gradient

        return self
    
    def predict(self, X):

        X = np.c_[np.ones((X.shape[0], 1)), X]
        return X.dot(self.weights)

    def r2_score(self, X, y):
        y_pred = self.predict(X)
        y_mean = np.mean(y)
        ss_res = np.sum((y - y_pred) ** 2)
        ss_tot = np.sum((y - y_mean) ** 2)
        return 1 - (ss_res / ss_tot)

Чтобы сделать модель детерминированной, нужно установить значение параметра random_state(seed) для фиксации случайности.

Сделаем прогноз с помощью нашей модели:

In [10]:
my_model = LinregSDG(random_state=21)
my_model.fit(X_train, y_train)
my_pred = my_model.predict(X_val)
my_pred_test = my_model.predict(X_test)

Оценим нашу модель:

In [11]:
my_mae = mean_absolute_error(y_val, my_pred)
my_rmse = np.sqrt(mean_squared_error(y_val, my_pred))
my_r2 = r2_score(y_val, my_pred)

my_mae_test = mean_absolute_error(y_test, my_pred_test)
my_rmse_test = np.sqrt(mean_squared_error(y_test, my_pred_test))
my_r2_test = r2_score(y_test, my_pred_test)

print(f"train:\n\nMAE={my_mae:.5f},\nRMSE={my_rmse:.5f},\nR2={my_r2:.5f}\n")
print(f"test:\n\nMAE={my_mae_test:.5f},\nRMSE={my_rmse_test:.5f},\nR2={my_r2_test:.5f}")

train:

MAE=689.34153,
RMSE=1024.24715,
R2=0.54617

test:

MAE=696.38861,
RMSE=1036.54225,
R2=0.54789

Сравним нашу модель с LinearRegression из sklearn:

In [12]:
linreg = LinearRegression()
linreg.fit(X_train, y_train)
lin_pred = linreg.predict(X_val)
lin_pred_test = linreg.predict(X_test)

In [13]:
mae = mean_absolute_error(y_val, lin_pred)
rmse = np.sqrt(mean_squared_error(y_val, lin_pred))
r2 = r2_score(y_val, lin_pred)

mae_test = mean_absolute_error(y_test, lin_pred_test)
rmse_test = np.sqrt(mean_squared_error(y_test, lin_pred_test))
r2_test = r2_score(y_test, lin_pred_test)

print(f"train:\n\nMAE={mae:.5f},\nRMSE={rmse:.5f},\nR2={r2:.5f}")
print(f"test:\n\nMAE={mae_test:.5f},\nRMSE={rmse_test:.5f},\nR2={r2_test:.5f}")

train:

MAE=691.14867,
RMSE=993.58971,
R2=0.57293
test:

MAE=698.31714,
RMSE=1007.16870,
R2=0.57315

Как мы видим показатели практически **одинаковые**

Сохраним результаты в таблицу:

In [14]:
mae_df = pd.DataFrame({
    'model': ['my_linreg', 'sklearn_linreg'],
    'train': [my_mae, mae],
    'test': [my_mae_test, mae_test]
})

rmse_df = pd.DataFrame({
    'model': ['my_linreg', 'sklearn_linreg'],
    'train': [my_rmse, rmse],
    'test': [my_rmse_test, rmse_test]
})

r2_df = pd.DataFrame({
    'model': ['my_linreg', 'sklearn_linreg'],
    'train': [my_r2, r2],
    'test': [my_r2_test, r2_test]
})

In [15]:
mae_df

            model       train        test
0       my_linreg  689.341534  696.388609
1  sklearn_linreg  691.148666  698.317139

In [16]:
rmse_df

            model        train         test
0       my_linreg  1024.247147  1036.542248
1  sklearn_linreg   993.589711  1007.168699

In [17]:
r2_df

            model     train      test
0       my_linreg  0.546170  0.547894
1  sklearn_linreg  0.572932  0.573155

## 5. Реализация регуляризованных моделей - Ridge, Lasso, ElasticNet

In [18]:
class BaseRegularizedLinreg:
    def __init__(self, alpha=0.01, l1_ratio=0.5, learning_rate=0.1, n_epoch=150, batch_size=64, random_state=None):
        self.alpha = alpha
        self.l1_ratio = l1_ratio
        self.learning_rate = learning_rate
        self.n_epoch = n_epoch
        self.batch_size = batch_size
        self.random_state = random_state
        self.theta = None

    def __add_bias(self, X):
    
        return np.c_[np.ones((X.shape[0], 1)), X]
    

    def _get_regularization_loss(self):
    
        raise NotImplementedError
    

    def _get_regularization_gradient(self, m):
    
        raise NotImplementedError
    

    def fit(self, X, y):

        if self.random_state is not None:
            np.random.seed(self.random_state)

        X = np.asarray(X, dtype=np.float64)
        y = np.asarray(y, dtype=np.float64)

        X_b = self.__add_bias(X)
        n_samples, n_features = X_b.shape
        self.theta = np.random.randn(n_features)

        for epoch in range(self.n_epoch):
            indices = np.random.permutation(n_samples)
            X_b_shuffled = X_b[indices]
            y_shuffled = y[indices]

            for i in range(0, n_samples, self.batch_size):
                X_batch = X_b_shuffled[i:i + self.batch_size]
                y_batch = y_shuffled[i:i + self.batch_size]

                m = len(y_batch)
                predictions = X_batch.dot(self.theta)
                erros = predictions - y_batch
                gradient = (2 / m) * X_batch.T.dot(erros)

                reg_gradient = self._get_regularization_gradient(m)
                gradient[1:] += reg_gradient

                self.theta -= self.learning_rate * gradient

        return self
    

    def predict(self, X):
        X_b = self.__add_bias(X)
        return X_b.dot(self.theta)
    

    def score(self, X, y):
        r2 = r2_score(y, self.predict(X))
        mse = mean_absolute_error(y, self.predict(X))
        rmse = np.sqrt(mean_squared_error(y, self.predict(X)))

        return r2, mse, rmse

    
    def get_params(self):

        return {
            'intercept': self.theta[0],
            'coefficients': self.theta[1:],
            'alpha': self.alpha
        }

In [19]:
class LassoLinreg(BaseRegularizedLinreg):

    def _get_regularization_gradient(self, m):
        return (self.alpha / m) * np.sign(self.theta[1:])

In [20]:
class RidgeLinreg(BaseRegularizedLinreg):

    def _get_regularization_gradient(self, m):
        return (2 * self.alpha / m) * self.theta[1:]

In [21]:
class ElasticNetLinreg(BaseRegularizedLinreg):

    def __init__(self, alpha=0.1, l1_ratio=0.5, **kwargs):
        super().__init__(alpha=alpha, **kwargs)
        self.l1_ratio = l1_ratio

    def _get_regularization_gradient(self, m):
        l2_gradient = (2 * self.alpha * (1 - self.l1_ratio) / m) * self.theta[1:]
        l1_gradient = (self.alpha * self.l1_ratio / m) * np.sign(self.theta[1:])
        return l2_gradient + l1_gradient
    
    def get_params(self):
        params =  super().get_params()
        params['l1_ratio'] = self.l1_ratio
        return params

Сделаем прогнозы с помощью наших моделей и моделей из sklearn'a:

In [22]:
models = {
    'my_Ridge': RidgeLinreg(alpha=1, learning_rate=0.1, n_epoch=150, random_state=21),
    'my_Lasso': LassoLinreg(alpha=1, learning_rate=0.1, n_epoch=150, random_state=21),
    'my_ElasticNet': ElasticNetLinreg(alpha=1, l1_ratio=0.5, learning_rate=0.1, n_epoch=150, random_state=21),
    'Ridge': Ridge(alpha=1, random_state=21, max_iter=1000),
    'Lasso': Lasso(alpha=1, random_state=21, max_iter=1000),
    'ElasticNet': ElasticNet(alpha=1, l1_ratio=0.5, random_state=21, max_iter=1000)
}

In [23]:
def count_metrics(models, X_train, X_val, X_test, y_train, y_val, y_test, mae_df, rmse_df, r2_df):
    for name, model in models.items():
        model.fit(X_train, y_train)
        y_pred_train = model.predict(X_val)
        y_pred_test = model.predict(X_test)

        mae = [name, mean_absolute_error(y_val, y_pred_train), mean_absolute_error(y_test, y_pred_test)]
        rmse =  [name, np.sqrt(mean_squared_error(y_val, y_pred_train)), np.sqrt(mean_squared_error(y_test, y_pred_test))]
        r2 = [name, r2_score(y_val, y_pred_train), r2_score(y_test, y_pred_test)]

        mae_df = pd.concat([mae_df, pd.DataFrame([mae], columns=mae_df.columns)], ignore_index=True)
        rmse_df = pd.concat([rmse_df, pd.DataFrame([rmse], columns=rmse_df.columns)], ignore_index=True)
        r2_df = pd.concat([r2_df, pd.DataFrame([r2], columns=r2_df.columns)], ignore_index=True)

    return mae_df, rmse_df, r2_df

In [24]:
mae_df, rmse_df, r2_df = count_metrics(
    models,
    X_train, X_val, X_test,
    y_train, y_val, y_test,
    mae_df, rmse_df, r2_df
    )

Сравним результаты:

In [25]:
mae_df

            model       train        test
0       my_linreg  689.341534  696.388609
1  sklearn_linreg  691.148666  698.317139
2        my_Ridge  683.335999  690.854551
3        my_Lasso  685.717484  692.322032
4   my_ElasticNet  683.973641  690.989732
5           Ridge  691.142122  698.311529
6           Lasso  690.379941  697.858250
7      ElasticNet  787.243755  801.029166

In [26]:
rmse_df

            model        train         test
0       my_linreg  1024.247147  1036.542248
1  sklearn_linreg   993.589711  1007.168699
2        my_Ridge  1013.173659  1025.359965
3        my_Lasso  1010.696353  1022.809621
4   my_ElasticNet  1011.318924  1023.473950
5           Ridge   993.589470  1007.168093
6           Lasso   993.520198  1007.150018
7      ElasticNet  1154.019677  1169.412023

In [27]:
r2_df

            model     train      test
0       my_linreg  0.546170  0.547894
1  sklearn_linreg  0.572932  0.573155
2        my_Ridge  0.555930  0.557597
3        my_Lasso  0.558099  0.559795
4   my_ElasticNet  0.557555  0.559223
5           Ridge  0.572932  0.573155
6           Lasso  0.572991  0.573171
7      ElasticNet  0.423884  0.424559

В полученных данных мы видим, что разницы практически нет

## 6. Нормализация функций

**Нормализация** - это процесс приведения признаков к единому маштабу. Без нее признаки с большими значениями могут доменировать над признаками с малыми значениями, что искажает работу модели.

Нормализация **обязательна** при работе с ***градиентным спуском***(без нормализации он будет "скакать"  по осям, обучение замедлится или не сойдется), ***регуляризацией***(если признаки будут в разных маштабах, то штраф будет несправедливым), методами основанными на расстояниях и др.

Нормализация **не нужна** в ситуациях, когда мы используем ***древовидные модели***(деревья разбивают по порогам, маштаб не влияет на разбиение), признаки уже в ***одном маштабе***, важна ***интерпретируемость***(нужно сохранить исходные единицы измерения)

### 6.1 MinMaxScaler

**MinMaxScaler** - метод нормализации, который преобразует признаки к диапазону [0,1] (или другому заданному диапазону)

$$ X_{scaled} = \frac{X - X_{min}}{X_{max} - X_{min}} $$

Где:
- **$X$** — исходное значение признака
- **$X_{min}$** — минимальное значение признака в обучающей выборке
- **$X_{max}$** — максимальное значение признака в обучающей выборке
- **$X_{scaled}$** — нормализованное значение (обычно в диапазоне [0, 1])

Если нужно вернуть данные к исходному масштабу:

$$ X_{original} = X_{scaled} \cdot (X_{max} - X_{min}) + X_{min} $$

Создадим собственную функцию для нормализации признаков с помощью MinMaxScaler

In [28]:
class MyMinMaxScaler:
    def __init__(self, feature_range=(0, 1)):
        self.feature_range = feature_range
        self.min_ = None
        self.max_ = None
        self.scale_ = None
        self.n_feaatures_ = None


    def fit(self, X):

        X = np.asarray(X, dtype=np.float64)

        if X.ndim == 1:
            X = X.reshape(-1, 1)     

        self.n_feaatures_ = X.shape[1]

        self.min_ = np.min(X, axis=0)
        self.max_ = np.max(X, axis=0)

        data_range = self.max_ - self.min_

        data_range[data_range == 0] = 1.0

        self.scale_ =  (self.feature_range[1] - self.feature_range[0]) / data_range

        return self

    def transform(self, X):
        if self.min_ is None or self.max_ is None:
            raise ValueError("Вызовите fit() перед transform()")
        
        X = np.asarray(X, dtype=np.float64)

        if X.ndim == 1:
            X = X.reshape(-1, 1)

        if X.shape[1] != self.n_feaatures_:
            raise ValueError(f"Ожидается {self.n_feaatures_} признаков. Получено {X.shape[1]}")
        
        X_scaled = (X - self.min_) * self.scale_ + self.feature_range[0]

        return X_scaled
    
    def fit_transform(self, X):

        return self.fit(X).transform(X)
    
    def inverse_transform(self, X):
        if self.min_ is None or self.max_ is None:
            raise ValueError("Сначала вызовите fit()")
        
        X = np.asarray(X, dtype=np.float64)

        if X.ndim == 1:
            X = X.reshape(-1, 1)

        X_original = (X - self.feature_range[0]) / self.scale_ + self.min_

        return X_original

In [29]:
mm_scaler = MyMinMaxScaler()
X_scaled_mm = mm_scaler.fit_transform(X_train)

In [30]:
X_scaled_mm_df = pd.DataFrame(
    X_scaled_mm,
    columns=X_train.columns,     
    index=X_train.index      
)

In [31]:
X_scaled_mm_df

,Elevator,Cats Allowed,Hardwood Floors,Dogs Allowed,Doorman,Dishwasher,No Fee,Laundry in Building,Fitness Center,Pre-War,...,Outdoor Space,Dining Room,High Speed Internet,Balcony,Swimming Pool,Laundry In Building,New Construction,Terrace,bathrooms,bedrooms
11673,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00
37933,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.75
45208,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.5,0.50
10389,1.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.25
16953,1.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16432,1.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.25
8964,1.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.25
5944,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,0.0,1.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.00
5327,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.75
15305,1.0,0.0,1.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.50

Сделаем тоже самое с помощью MinMaxScaler из sklearn:

In [32]:
mm_scaler_sclearn = MinMaxScaler()
X_scaled_mm_sclearn = mm_scaler_sclearn.fit_transform(X_train)
X_scaled_mm_sclearn_val = mm_scaler_sclearn.transform(X_val)
X_scaled_mm_sclearn_test = mm_scaler_sclearn.transform(X_test)
X_scaled_mm_df_sclearn = pd.DataFrame(
    X_scaled_mm_sclearn,
    columns=X_train.columns,     
    index=X_train.index      
)

In [33]:
X_scaled_mm_df_sclearn

,Elevator,Cats Allowed,Hardwood Floors,Dogs Allowed,Doorman,Dishwasher,No Fee,Laundry in Building,Fitness Center,Pre-War,...,Outdoor Space,Dining Room,High Speed Internet,Balcony,Swimming Pool,Laundry In Building,New Construction,Terrace,bathrooms,bedrooms
11673,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00
37933,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.75
45208,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.5,0.50
10389,1.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.25
16953,1.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16432,1.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.25
8964,1.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.25
5944,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,0.0,1.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.00
5327,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.75
15305,1.0,0.0,1.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.50

Признаки изменились одинаково

### 6.2 StandartScaler

**StandardScaler** — это метод нормализации, который преобразует признаки к распределению с средним 0 и стандартным отклонением 1.

$$ X_{scaled} = \frac{X - \mu}{\sigma} $$

Где:
- **$X$** — исходное значение признака
- **$\mu$** (mu) — среднее значение признака в обучающей выборке (mean)
- **$\sigma$** (sigma) — стандартное отклонение признака в обучающей выборке (std)
- **$X_{scaled}$** — нормализованное значение (среднее = 0, стд. отклонение = 1)

Если нужно вернуть данные к исходному масштабу:

$$ X_{original} = X_{scaled} \cdot \sigma + \mu $$

In [34]:
class MyStandartScaler:
    def __init__(self):
        self.mean_ = None
        self.std_ = None
        self.n_features_ = None

    def fit(self, X):
        X = np.asarray(X, dtype=np.float64)

        if X.ndim ==1:
            X = X.reshape(-1, 1)

        self.n_features_ = X.shape[1]
        self.mean_ = np.mean(X, axis=0)
        self.std_ = np.std(X, axis=0)

        self.std_[self.std_ == 0] = 1

        return self
    
    def transform(self, X):
        if self.mean_ is None or self.std_ is None:
            raise ValueError("Сначала вызовите fit()")
        
        X = np.asarray(X, dtype=np.float64)

        if X.ndim == 1:
            X = X.reshape(-1, 1)

        X_scaled = (X - self.mean_) / self.std_

        return X_scaled
    
    def fit_transform(self, X):
        return self.fit(X).transform(X)
    
    def inverse_transform(self, X):
        if self.mean_ is None or self.std_ is None:
            raise ValueError("Сначала fit()")
        
        X = np.asarray(X, dtype=np.float64)

        if X.ndim == 1:
            X = X.reshape(-1, 1)

        X_original = X * self.std_ + self.mean_

        return X_original

Преобразуем данные и сравним результаты с sklearn StandardScaler

In [35]:
my_std_scaler = MyStandartScaler()
X_scaled_my_std = my_std_scaler.fit_transform(X_train)
X_scaled_my_std_df = pd.DataFrame(
    X_scaled_my_std,
    columns=X_train.columns,
    index=X_train.index
)
X_scaled_my_std_df

,Elevator,Cats Allowed,Hardwood Floors,Dogs Allowed,Doorman,Dishwasher,No Fee,Laundry in Building,Fitness Center,Pre-War,...,Outdoor Space,Dining Room,High Speed Internet,Balcony,Swimming Pool,Laundry In Building,New Construction,Terrace,bathrooms,bedrooms
11673,0.950386,-0.964753,1.041711,-0.907399,1.162431,-0.845154,-0.764441,-0.705899,-0.607763,-0.478660,...,-0.34187,-0.334950,-0.311074,-0.251308,-0.241202,-0.236979,-0.236424,-0.216555,-0.457327,-1.423143
37933,0.950386,1.036535,1.041711,1.102052,1.162431,1.183216,1.308145,1.416633,1.645378,2.089164,...,-0.34187,-0.334950,-0.311074,-0.251308,-0.241202,-0.236979,-0.236424,-0.216555,-0.457327,1.385639
45208,0.950386,-0.964753,1.041711,-0.907399,1.162431,1.183216,-0.764441,1.416633,1.645378,-0.478660,...,-0.34187,-0.334950,-0.311074,-0.251308,-0.241202,-0.236979,-0.236424,-0.216555,1.911224,0.449379
10389,0.950386,1.036535,-0.959959,1.102052,1.162431,-0.845154,-0.764441,-0.705899,1.645378,-0.478660,...,-0.34187,-0.334950,-0.311074,-0.251308,-0.241202,-0.236979,-0.236424,-0.216555,-0.457327,-0.486882
16953,0.950386,1.036535,-0.959959,1.102052,1.162431,-0.845154,-0.764441,-0.705899,-0.607763,-0.478660,...,-0.34187,-0.334950,-0.311074,-0.251308,-0.241202,4.219775,-0.236424,-0.216555,-0.457327,-1.423143
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16432,0.950386,1.036535,-0.959959,1.102052,1.162431,-0.845154,1.308145,-0.705899,1.645378,-0.478660,...,-0.34187,-0.334950,-0.311074,-0.251308,-0.241202,4.219775,-0.236424,-0.216555,-0.457327,-0.486882
8964,0.950386,1.036535,-0.959959,1.102052,1.162431,-0.845154,-0.764441,-0.705899,-0.607763,-0.478660,...,-0.34187,-0.334950,-0.311074,-0.251308,-0.241202,-0.236979,-0.236424,-0.216555,-0.457327,-0.486882
5944,-1.052204,1.036535,1.041711,1.102052,1.162431,1.183216,1.308145,1.416633,1.645378,2.089164,...,-0.34187,2.985517,3.214673,3.979177,-0.241202,-0.236979,4.229682,-0.216555,-0.457327,-1.423143
5327,-1.052204,1.036535,-0.959959,1.102052,-0.860266,-0.845154,1.308145,1.416633,-0.607763,-0.478660,...,-0.34187,-0.334950,-0.311074,-0.251308,-0.241202,-0.236979,-0.236424,-0.216555,-0.457327,1.385639
15305,0.950386,-0.964753,1.041711,-0.907399,1.162431,1.183216,1.308145,1.416633,-0.607763,2.089164,...,-0.34187,-0.334950,-0.311074,-0.251308,-0.241202,-0.236979,-0.236424,-0.216555,-0.457327,0.449379

In [36]:
std_sc = StandardScaler()
scaled_std_sc = std_sc.fit_transform(X_train)
scaled_std_sc_df = pd.DataFrame(
    scaled_std_sc,
    columns=X_train.columns,
    index=X_train.index
)
scaled_std_sc_df

,Elevator,Cats Allowed,Hardwood Floors,Dogs Allowed,Doorman,Dishwasher,No Fee,Laundry in Building,Fitness Center,Pre-War,...,Outdoor Space,Dining Room,High Speed Internet,Balcony,Swimming Pool,Laundry In Building,New Construction,Terrace,bathrooms,bedrooms
11673,0.950386,-0.964753,1.041711,-0.907399,1.162431,-0.845154,-0.764441,-0.705899,-0.607763,-0.478660,...,-0.34187,-0.334950,-0.311074,-0.251308,-0.241202,-0.236979,-0.236424,-0.216555,-0.457327,-1.423143
37933,0.950386,1.036535,1.041711,1.102052,1.162431,1.183216,1.308145,1.416633,1.645378,2.089164,...,-0.34187,-0.334950,-0.311074,-0.251308,-0.241202,-0.236979,-0.236424,-0.216555,-0.457327,1.385639
45208,0.950386,-0.964753,1.041711,-0.907399,1.162431,1.183216,-0.764441,1.416633,1.645378,-0.478660,...,-0.34187,-0.334950,-0.311074,-0.251308,-0.241202,-0.236979,-0.236424,-0.216555,1.911224,0.449379
10389,0.950386,1.036535,-0.959959,1.102052,1.162431,-0.845154,-0.764441,-0.705899,1.645378,-0.478660,...,-0.34187,-0.334950,-0.311074,-0.251308,-0.241202,-0.236979,-0.236424,-0.216555,-0.457327,-0.486882
16953,0.950386,1.036535,-0.959959,1.102052,1.162431,-0.845154,-0.764441,-0.705899,-0.607763,-0.478660,...,-0.34187,-0.334950,-0.311074,-0.251308,-0.241202,4.219775,-0.236424,-0.216555,-0.457327,-1.423143
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16432,0.950386,1.036535,-0.959959,1.102052,1.162431,-0.845154,1.308145,-0.705899,1.645378,-0.478660,...,-0.34187,-0.334950,-0.311074,-0.251308,-0.241202,4.219775,-0.236424,-0.216555,-0.457327,-0.486882
8964,0.950386,1.036535,-0.959959,1.102052,1.162431,-0.845154,-0.764441,-0.705899,-0.607763,-0.478660,...,-0.34187,-0.334950,-0.311074,-0.251308,-0.241202,-0.236979,-0.236424,-0.216555,-0.457327,-0.486882
5944,-1.052204,1.036535,1.041711,1.102052,1.162431,1.183216,1.308145,1.416633,1.645378,2.089164,...,-0.34187,2.985517,3.214673,3.979177,-0.241202,-0.236979,4.229682,-0.216555,-0.457327,-1.423143
5327,-1.052204,1.036535,-0.959959,1.102052,-0.860266,-0.845154,1.308145,1.416633,-0.607763,-0.478660,...,-0.34187,-0.334950,-0.311074,-0.251308,-0.241202,-0.236979,-0.236424,-0.216555,-0.457327,1.385639
15305,0.950386,-0.964753,1.041711,-0.907399,1.162431,1.183216,1.308145,1.416633,-0.607763,2.089164,...,-0.34187,-0.334950,-0.311074,-0.251308,-0.241202,-0.236979,-0.236424,-0.216555,-0.457327,0.449379

Результаты **идентичны**

Нормализуем все остальные данные

In [37]:
stsc = StandardScaler()
X_train_scaled = stsc.fit_transform(X_train)
X_val_scaled = stsc.transform(X_val)
X_test_scaled = stsc.transform(X_test)

## 7. Обучение моделей на нормализованных данных

### 7.1 Обучение с помощью MinMaxScaler

In [38]:
models_for_minmax = {
    'Linreg MinMaxScaler': LinearRegression(),
    'Ridge MinMaxScaler': Ridge(),
    'Lasso MinMaxScaler': Lasso(alpha=0.1),
    'ElasticNet MinMaxScaler': ElasticNet()
}

mae_df, rmse_df, r2_df = count_metrics(
    models_for_minmax,
    X_scaled_mm_sclearn, X_scaled_mm_sclearn_val, X_scaled_mm_sclearn_test,
    y_train, y_val, y_test,
    mae_df, rmse_df, r2_df
)

### 7.2 Обучение с помощью StandartScaler

In [39]:
models_for_stdsc = {
    'Linreg StandartScaler': LinearRegression(),
    'Ridge StandartScaler': Ridge(),
    'Lasso StandartScaler': Lasso(),
    'ElasticNet StandartScaler': ElasticNet()
}

mae_df, rmse_df, r2_df = count_metrics(
    models_for_stdsc,
    X_train_scaled, X_val_scaled, X_test_scaled,
    y_train, y_val, y_test,
    mae_df, rmse_df, r2_df
)

In [40]:
mae_df

                        model       train        test
0                   my_linreg  689.341534  696.388609
1              sklearn_linreg  691.148666  698.317139
2                    my_Ridge  683.335999  690.854551
3                    my_Lasso  685.717484  692.322032
4               my_ElasticNet  683.973641  690.989732
5                       Ridge  691.142122  698.311529
6                       Lasso  690.379941  697.858250
7                  ElasticNet  787.243755  801.029166
8         Linreg MinMaxScaler  691.148666  698.317139
9          Ridge MinMaxScaler  691.144131  698.309635
10         Lasso MinMaxScaler  691.058689  698.248606
11    ElasticNet MinMaxScaler  956.867051  969.153709
12      Linreg StandartScaler  691.148666  698.317139
13       Ridge StandartScaler  691.147782  698.316236
14       Lasso StandartScaler  690.858179  698.119609
15  ElasticNet StandartScaler  719.281981  727.156225

In [41]:
rmse_df

                        model        train         test
0                   my_linreg  1024.247147  1036.542248
1              sklearn_linreg   993.589711  1007.168699
2                    my_Ridge  1013.173659  1025.359965
3                    my_Lasso  1010.696353  1022.809621
4               my_ElasticNet  1011.318924  1023.473950
5                       Ridge   993.589470  1007.168093
6                       Lasso   993.520198  1007.150018
7                  ElasticNet  1154.019677  1169.412023
8         Linreg MinMaxScaler   993.589711  1007.168699
9          Ridge MinMaxScaler   993.593148  1007.167737
10         Lasso MinMaxScaler   993.565830  1007.146052
11    ElasticNet MinMaxScaler  1345.783030  1362.156114
12      Linreg StandartScaler   993.589711  1007.168699
13       Ridge StandartScaler   993.589695  1007.168588
14       Lasso StandartScaler   993.537380  1007.134015
15  ElasticNet StandartScaler  1037.445608  1050.044312

In [42]:
r2_df

                        model     train      test
0                   my_linreg  0.546170  0.547894
1              sklearn_linreg  0.572932  0.573155
2                    my_Ridge  0.555930  0.557597
3                    my_Lasso  0.558099  0.559795
4               my_ElasticNet  0.557555  0.559223
5                       Ridge  0.572932  0.573155
6                       Lasso  0.572991  0.573171
7                  ElasticNet  0.423884  0.424559
8         Linreg MinMaxScaler  0.572932  0.573155
9          Ridge MinMaxScaler  0.572929  0.573156
10         Lasso MinMaxScaler  0.572952  0.573174
11    ElasticNet MinMaxScaler  0.216510  0.219236
12      Linreg StandartScaler  0.572932  0.573155
13       Ridge StandartScaler  0.572932  0.573155
14       Lasso StandartScaler  0.572976  0.573184
15  ElasticNet StandartScaler  0.534399  0.536039

## 8. Переобучение модели

Создадим новые полиноминальные признаки для нашего набора данных

In [43]:
cols_to_poly = ['bathrooms', 'bedrooms']
cols_to_keep = X_train.drop(columns=cols_to_poly)

poly = PolynomialFeatures(degree=10, include_bias=False)

poly_features = poly.fit_transform(X_train[cols_to_poly])
poly_names = poly.get_feature_names_out(cols_to_poly)
df_poly = pd.DataFrame(poly_features, columns=poly_names, index=X_train.index)
X_poly_train = pd.concat([cols_to_keep, df_poly], axis=1)

poly_features_valid = poly.transform(X_val[cols_to_poly])
df_poly_valid = pd.DataFrame(poly_features_valid, columns=poly_names, index=X_val.index)
X_poly_valid = pd.concat([X_val.drop(columns=cols_to_poly), df_poly_valid], axis=1)

poly_features_test = poly.transform(X_test[cols_to_poly])
df_poly_test = pd.DataFrame(poly_features_test, columns=poly_names, index=X_test.index)
X_poly_test = pd.concat([X_test.drop(columns=cols_to_poly), df_poly_test], axis=1)

X_poly_train

,Elevator,Cats Allowed,Hardwood Floors,Dogs Allowed,Doorman,Dishwasher,No Fee,Laundry in Building,Fitness Center,Pre-War,...,bathrooms^9 bedrooms,bathrooms^8 bedrooms^2,bathrooms^7 bedrooms^3,bathrooms^6 bedrooms^4,bathrooms^5 bedrooms^5,bathrooms^4 bedrooms^6,bathrooms^3 bedrooms^7,bathrooms^2 bedrooms^8,bathrooms bedrooms^9,bedrooms^10
11673,1,0,1,0,1,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
37933,1,1,1,1,1,1,1,1,1,1,...,3.0,9.0,27.0,81.0,243.0,729.0,2187.0,6561.0,19683.0,59049.0
45208,1,0,1,0,1,1,0,1,1,0,...,1024.0,1024.0,1024.0,1024.0,1024.0,1024.0,1024.0,1024.0,1024.0,1024.0
10389,1,1,0,1,1,0,0,0,1,0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
16953,1,1,0,1,1,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16432,1,1,0,1,1,0,1,0,1,0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
8964,1,1,0,1,1,0,0,0,0,0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
5944,0,1,1,1,1,1,1,1,1,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5327,0,1,0,1,0,0,1,1,0,0,...,3.0,9.0,27.0,81.0,243.0,729.0,2187.0,6561.0,19683.0,59049.0
15305,1,0,1,0,1,1,1,1,0,1,...,2.0,4.0,8.0,16.0,32.0,64.0,128.0,256.0,512.0,1024.0

Обучим и протестируем наши модели на полиноминальных признаках

In [44]:
models_for_poly = {
    'Linreg poly': LinearRegression(),
    'Ridge poly': Ridge(),
    'Lasso poly': Lasso(),
    'ElasticNet poly': ElasticNet()
}

mae_df, rmse_df, r2_df = count_metrics(
    models_for_poly,
    X_poly_train, X_poly_valid, X_poly_test,
    y_train, y_val, y_test,
    mae_df, rmse_df, r2_df
)

/home/aslan/Desktop/S21/DS/ML2_Supervised_learning.ID_1254799-1/env/lib/python3.12/site-packages/sklearn/linear_model/_ridge.py:228: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 9.324991599326766e-17.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/home/aslan/Desktop/S21/DS/ML2_Supervised_learning.ID_1254799-1/env/lib/python3.12/site-packages/sklearn/linear_model/_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.869e+10, tolerance: 9.095e+06
  model = cd_fast.enet_coordinate_descent(
/home/aslan/Desktop/S21/DS/ML2_Supervised_learning.ID_1254799-1/env/lib/python3.12/site-packages/sklearn/linear_model/_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.096e+10, tolerance: 9.095e+06
  model = cd_fast.enet_coordinate_descent(

In [45]:
mae_df

                        model       train        test
0                   my_linreg  689.341534  696.388609
1              sklearn_linreg  691.148666  698.317139
2                    my_Ridge  683.335999  690.854551
3                    my_Lasso  685.717484  692.322032
4               my_ElasticNet  683.973641  690.989732
5                       Ridge  691.142122  698.311529
6                       Lasso  690.379941  697.858250
7                  ElasticNet  787.243755  801.029166
8         Linreg MinMaxScaler  691.148666  698.317139
9          Ridge MinMaxScaler  691.144131  698.309635
10         Lasso MinMaxScaler  691.058689  698.248606
11    ElasticNet MinMaxScaler  956.867051  969.153709
12      Linreg StandartScaler  691.148666  698.317139
13       Ridge StandartScaler  691.147782  698.316236
14       Lasso StandartScaler  690.858179  698.119609
15  ElasticNet StandartScaler  719.281981  727.156225
16                Linreg poly  675.769448  693.643830
17                 Ridge poly  675.760794  693.476039
18                 Lasso poly  675.738512  683.800634
19            ElasticNet poly  706.754238  716.325149

In [46]:
rmse_df

                        model        train         test
0                   my_linreg  1024.247147  1036.542248
1              sklearn_linreg   993.589711  1007.168699
2                    my_Ridge  1013.173659  1025.359965
3                    my_Lasso  1010.696353  1022.809621
4               my_ElasticNet  1011.318924  1023.473950
5                       Ridge   993.589470  1007.168093
6                       Lasso   993.520198  1007.150018
7                  ElasticNet  1154.019677  1169.412023
8         Linreg MinMaxScaler   993.589711  1007.168699
9          Ridge MinMaxScaler   993.593148  1007.167737
10         Lasso MinMaxScaler   993.565830  1007.146052
11    ElasticNet MinMaxScaler  1345.783030  1362.156114
12      Linreg StandartScaler   993.589711  1007.168699
13       Ridge StandartScaler   993.589695  1007.168588
14       Lasso StandartScaler   993.537380  1007.134015
15  ElasticNet StandartScaler  1037.445608  1050.044312
16                Linreg poly   967.632523  1627.395892
17                 Ridge poly   967.629267  1613.342087
18                 Lasso poly   971.167476   993.748420
19            ElasticNet poly  1011.696415  1034.515281

In [47]:
r2_df

                        model     train      test
0                   my_linreg  0.546170  0.547894
1              sklearn_linreg  0.572932  0.573155
2                    my_Ridge  0.555930  0.557597
3                    my_Lasso  0.558099  0.559795
4               my_ElasticNet  0.557555  0.559223
5                       Ridge  0.572932  0.573155
6                       Lasso  0.572991  0.573171
7                  ElasticNet  0.423884  0.424559
8         Linreg MinMaxScaler  0.572932  0.573155
9          Ridge MinMaxScaler  0.572929  0.573156
10         Lasso MinMaxScaler  0.572952  0.573174
11    ElasticNet MinMaxScaler  0.216510  0.219236
12      Linreg StandartScaler  0.572932  0.573155
13       Ridge StandartScaler  0.572932  0.573155
14       Lasso StandartScaler  0.572976  0.573184
15  ElasticNet StandartScaler  0.534399  0.536039
16                Linreg poly  0.594954 -0.114429
17                 Ridge poly  0.594957 -0.095264
18                 Lasso poly  0.591989  0.584454
19            ElasticNet poly  0.557224  0.549661

Модели с полиноминальными признаками показали плохие результаты на тестовых данных т.к. были переобучены, однако Lasso Polly показала отличный результат, из чего можно сделать, что регуляризация L1 хорошо справляется с переобучением модели при мультиколинеарности признаков.

## 9. Собственные модели

In [48]:
mean_valid_val = y_val.mean()
mean_test_val = y_test.mean()

median_valid_val = y_val.median()
median_test_val = y_test.median()

mean_valid = np.full_like(y_val, mean_valid_val)
mean_test = np.full_like(y_test, mean_test_val)
median_valid = np.full_like(y_val, median_valid_val)
median_test = np.full_like(y_test, median_test_val)

mae_mean_valid = mean_absolute_error(y_val, mean_valid)
mae_mean_test = mean_absolute_error(y_test, mean_test)
mae_median_valid = mean_absolute_error(y_val, median_valid)
mae_median_test = mean_absolute_error(y_test, median_test)

rmse_mean_valid = np.sqrt(mean_squared_error(y_val, mean_valid))
rmse_mean_test = np.sqrt(mean_squared_error(y_test, mean_test))
rmse_median_valid = np.sqrt(mean_squared_error(y_val, median_valid))
rmse_median_test = np.sqrt(mean_squared_error(y_test, median_test))

r2_mean_valid = r2_score(y_val, mean_valid)
r2_mean_test = r2_score(y_test, mean_test)
r2_median_valid = r2_score(y_val, median_valid)
r2_median_test = r2_score(y_test, median_test)

mae_df_tmp = pd.DataFrame({
    'model': ['mean', 'median'],
    'train': [mae_mean_valid, mae_median_valid],
    'test': [mae_mean_test, mae_median_test]
    })

rmse_df_tmp = pd.DataFrame({
    'model': ['mean', 'median'],
    'train': [rmse_mean_valid, rmse_median_valid],
    'test': [rmse_mean_test, rmse_median_test]
})

#r2_df_tmp = pd.DataFrame({
#    'model': ['mean', 'median'],
#    'train': [r2_mean_valid, r2_median_valid],
#    'test': [r2_mean_test, r2_median_test]
#})

mae_df = pd.concat([mae_df, mae_df_tmp], ignore_index=True, axis=0,)
rmse_df = pd.concat([rmse_df, rmse_df_tmp], ignore_index=True, axis=0)
#r2_df = pd.concat([r2_df, r2_df_tmp], ignore_index=True, axis=0)

## 10. Сравним результаты

In [49]:
mae_df

                        model        train         test
0                   my_linreg   689.341534   696.388609
1              sklearn_linreg   691.148666   698.317139
2                    my_Ridge   683.335999   690.854551
3                    my_Lasso   685.717484   692.322032
4               my_ElasticNet   683.973641   690.989732
5                       Ridge   691.142122   698.311529
6                       Lasso   690.379941   697.858250
7                  ElasticNet   787.243755   801.029166
8         Linreg MinMaxScaler   691.148666   698.317139
9          Ridge MinMaxScaler   691.144131   698.309635
10         Lasso MinMaxScaler   691.058689   698.248606
11    ElasticNet MinMaxScaler   956.867051   969.153709
12      Linreg StandartScaler   691.148666   698.317139
13       Ridge StandartScaler   691.147782   698.316236
14       Lasso StandartScaler   690.858179   698.119609
15  ElasticNet StandartScaler   719.281981   727.156225
16                Linreg poly   675.769448   693.643830
17                 Ridge poly   675.760794   693.476039
18                 Lasso poly   675.738512   683.800634
19            ElasticNet poly   706.754238   716.325149
20                       mean  1087.798094  1108.168277
21                     median  1044.014661  1062.160412

In [50]:
rmse_df

                        model        train         test
0                   my_linreg  1024.247147  1036.542248
1              sklearn_linreg   993.589711  1007.168699
2                    my_Ridge  1013.173659  1025.359965
3                    my_Lasso  1010.696353  1022.809621
4               my_ElasticNet  1011.318924  1023.473950
5                       Ridge   993.589470  1007.168093
6                       Lasso   993.520198  1007.150018
7                  ElasticNet  1154.019677  1169.412023
8         Linreg MinMaxScaler   993.589711  1007.168699
9          Ridge MinMaxScaler   993.593148  1007.167737
10         Lasso MinMaxScaler   993.565830  1007.146052
11    ElasticNet MinMaxScaler  1345.783030  1362.156114
12      Linreg StandartScaler   993.589711  1007.168699
13       Ridge StandartScaler   993.589695  1007.168588
14       Lasso StandartScaler   993.537380  1007.134015
15  ElasticNet StandartScaler  1037.445608  1050.044312
16                Linreg poly   967.632523  1627.395892
17                 Ridge poly   967.629267  1613.342087
18                 Lasso poly   971.167476   993.748420
19            ElasticNet poly  1011.696415  1034.515281
20                       mean  1520.401894  1541.583985
21                     median  1557.724768  1582.606001

In [51]:
r2_df.sort_values(['test'], ascending=False)

                        model     train      test
18                 Lasso poly  0.591989  0.584454
14       Lasso StandartScaler  0.572976  0.573184
10         Lasso MinMaxScaler  0.572952  0.573174
6                       Lasso  0.572991  0.573171
9          Ridge MinMaxScaler  0.572929  0.573156
5                       Ridge  0.572932  0.573155
13       Ridge StandartScaler  0.572932  0.573155
8         Linreg MinMaxScaler  0.572932  0.573155
1              sklearn_linreg  0.572932  0.573155
12      Linreg StandartScaler  0.572932  0.573155
3                    my_Lasso  0.558099  0.559795
4               my_ElasticNet  0.557555  0.559223
2                    my_Ridge  0.555930  0.557597
19            ElasticNet poly  0.557224  0.549661
0                   my_linreg  0.546170  0.547894
15  ElasticNet StandartScaler  0.534399  0.536039
7                  ElasticNet  0.423884  0.424559
11    ElasticNet MinMaxScaler  0.216510  0.219236
17                 Ridge poly  0.594957 -0.095264
16                Linreg poly  0.594954 -0.114429

Исходя из полученных данных можем сделать вывод, что наиболее стабильная и точная модель - Lasso